public class RecruitingAppConstants {
    public static final String INPROGRESS_STATUS = 'In-Process';
    public static final String VALIDATED_STATUS = 'Validated by HR';
    public static final String CANCELLED_STATUS = 'Cancelled';
    public static final String CLOSED_STATUS = 'Closed';
    public static final String CANT_ASSIGN_TEXT = 'You can\'t assign candidates to vacancy with not In-Progress status.';
    public static final String NO_CANDIDATES_TEXT = 'There aren\'t candidates with status Validated by HR.';
    public static final String CANT_CLOSE_TEXT = 'You can\'t assign candidates to vacancy with not In-Progress status.';
    public static final String NO_CANDIDATES_TO_CLOSE_TEXT = 'You can\'t close vacancy without candidate. The vacancy will be canceled.';
}